# Generated by Django 4.2.6 on 2023-11-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_service', '0002_remove_client_full_name_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='newsletter_service.client', verbose_name='Клиенты'),
        ),
    ]
