# Generated by Django 4.2.6 on 2023-11-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_service', '0004_alter_client_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='send_time',
            field=models.DateTimeField(verbose_name='Время отправки'),
        ),
    ]
